const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const {load}=require('./lens-helpers.cjs');
const {annotateNativePerks}=load('native-perk-bridge');
const dom=new JSDOM('<div class="item-popup"><div id="one"><svg><image href="one.png" /></svg></div><div id="two"><svg><image href="two.png" /></svg></div><div id="stale" data-rl-plug-hash="999" data-rl-plug-slot="barrel"></div></div>');
const popup=dom.window.document.querySelector('.item-popup');
const first=popup.querySelector('#one'),second=popup.querySelector('#two');
first.__reactFiber$test={return:{memoizedProps:{plug:{plugDef:{hash:1}},socketInfo:{socketIndex:1}}}};
second.__reactFiber$test={return:{memoizedProps:{plug:{plugDef:{hash:3}},socketInfo:{socketIndex:4}}}};
const owned={slots:{barrel:{plugs:[{hash:1}]},mag:{plugs:[]},perk1:{plugs:[{hash:3}]},perk2:{plugs:[{hash:3}]},masterwork:{plugs:[]}}};
let clicks=0;first.addEventListener('click',()=>clicks++);
annotateNativePerks(popup,owned);
assert.equal(first.dataset.rlPlugHash,'1');assert.equal(first.dataset.rlPlugSlot,'barrel');
assert.equal(second.dataset.rlPlugSlot,'perk2','Identical plug hashes in two columns require exact native socket evidence');
assert.equal(popup.querySelector('#stale').dataset.rlPlugHash,undefined);
first.click();assert.equal(clicks,1,'Native handlers stay intact');
const observer=new dom.window.MutationObserver(()=>{});observer.observe(popup,{attributes:true,subtree:true});annotateNativePerks(popup,owned);assert.equal(observer.takeRecords().length,0,'Equivalent bridge scans settle');
first.__reactFiber$test.return.memoizedProps.plug.plugDef.hash=999;annotateNativePerks(popup,owned);assert.equal(first.dataset.rlPlugHash,undefined,'Replaced native icons lose stale identities');
observer.disconnect();dom.window.close();console.log('Native bridge checks passed: SVG identity, exact columns, stale cleanup, handler preservation and DOM settling.');
