const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const { load, payload, ownedRoll, sheet } = require('./lens-helpers.cjs');
const dom = new JSDOM('<!doctype html><body><div class="item-popup" data-aegis-instance-id="first"><h1>Native title</h1></div></body>', {pretendToBeVisual:true});
global.document = dom.window.document; global.HTMLElement = dom.window.HTMLElement;
const style=document.createElement('style');style.textContent=fs.readFileSync('public/roll-lens.css','utf8');document.head.append(style);
const { evaluateLens, activityRecommendations } = load('roll-lens');
const { applyLens, configureLens } = load('roll-lens-ui');
const { rollInspectorHtml, clearRollInspector } = load('roll-inspector');
const popup = document.querySelector('.item-popup');
popup.style.pointerEvents='none'; // DIM's desktop popup root, outside its native body/actions.
const near = payload(ownedRoll(['selectable','active','missing','active']), ownedRoll());
near.ownedRoll.slots.barrel.plugs.push({hash:101,name:'Other barrel',icon:'',active:true});
near.sheetWeaponPvECandidates = [{...sheet,barrel:'Barrel / Unowned barrel'}];
applyLens(popup,near);
let panel = document.getElementById('rl-roll-inspector');
assert.equal(panel.parentElement,popup,'The sidebar shares the native popup lifecycle');
assert.equal(dom.window.getComputedStyle(panel).pointerEvents,'auto','The guide must receive physical mouse/wheel events through DIM\'s non-interactive root');
assert.equal(dom.window.getComputedStyle(panel).position,'fixed','The guide docks to the viewport independently of the popup');
assert.equal(panel.querySelectorAll('.rl-inspector-activity').length,2);
for(const type of ['armor','other']) {
  const tile=document.createElement('div');tile.dataset.aegisItemType=type;document.body.append(tile);applyLens(tile,near);
  assert.equal(document.getElementById('rl-roll-inspector'),panel,'Unrelated nonweapon tiles cannot close the weapon guide');
  tile.remove();
}
assert.match(panel.querySelector('.rl-inspector-pve .rl-inspector-reason').textContent,/Missing: Trait 1/);
assert.match(panel.querySelector('[data-slot="perk1"] .rl-inspector-actual').textContent,/Other option/);
assert.match(panel.querySelector('[data-slot="perk1"] .rl-inspector-recommended').textContent,/Trait A/);
assert.ok(panel.querySelector('[data-slot="barrel"] .rl-choice-owned'),'Inactive owned options receive checks');
assert.match(panel.querySelector('[data-slot="barrel"] .rl-inspector-actual').textContent,/Barrel \/ Other barrel/);
assert.equal(panel.querySelectorAll('[data-slot="barrel"] .rl-choice-owned').length,2,'Unowned alternatives never receive a check');
const observer = new dom.window.MutationObserver(()=>{}); observer.observe(popup,{subtree:true,attributes:true,childList:true});
applyLens(popup,near); assert.equal(observer.takeRecords().length,0,'Unchanged popups settle without writes'); observer.disconnect();
const all = payload(ownedRoll(),ownedRoll());
const a = {...sheet,barrel:'Different barrel'}, b = {...sheet,mag:'Different mag'};
all.sheetWeaponPvECandidates = [a,b];
assert.equal(evaluateLens(all).pve.matchedCount,4,'Alternative rows cannot combine into a god roll');
const host = document.createElement('div'); host.innerHTML = rollInspectorHtml(all);
const combos = host.querySelectorAll('.rl-inspector-pve .rl-inspector-combination');
assert.equal(combos.length,2); assert.equal(combos[0].open,true); assert.equal(combos[1].open,false);
assert.match(combos[0].textContent,/Missing: Barrel/); assert.match(combos[1].textContent,/Missing: Magazine/);
assert.match(host.querySelector('.rl-inspector-activity.rl-inspector-pvp').textContent,/5\/5 · God roll/);
const selectedFlip = structuredClone(near);
for(const socket of Object.values(selectedFlip.ownedRoll.slots))for(const p of socket.plugs)p.active=!p.active;
assert.equal(rollInspectorHtml(selectedFlip),rollInspectorHtml(near),'Selected status does not change guide content');
const notes=panel.querySelector('.rl-inspector-notes');notes.open=true;applyLens(popup,selectedFlip);
assert.equal(panel.querySelector('.rl-inspector-notes'),notes,'Selection changes preserve the reader\'s expanded notes');
assert.equal(notes.open,true);
// Updates with the same score must still replace the actual, non-matching choices.
near.ownedRoll.slots.perk1.plugs[0].name='Changed unowned trait'; applyLens(popup,near);
assert.match(panel.querySelector('[data-slot="perk1"] .rl-inspector-actual').textContent,/Changed unowned trait/);
let nativeClicks=0; popup.addEventListener('click',()=>nativeClicks++);
panel.querySelector('.rl-inspector-close').click();
assert.equal(document.getElementById('rl-roll-inspector'),null); assert.equal(nativeClicks,0);
applyLens(popup,near); assert.equal(document.getElementById('rl-roll-inspector'),null,'Dismissed guide stays closed for that item');
popup.dataset.aegisInstanceId='second'; applyLens(popup,near);
panel=document.getElementById('rl-roll-inspector'); assert.ok(panel,'A different weapon instance opens its own guide');
assert.equal(document.querySelectorAll('#rl-roll-inspector').length,1);
configureLens({enabled:false}); assert.equal(document.getElementById('rl-roll-inspector'),null);
configureLens({enabled:true}); applyLens(popup,near);
popup.remove(); assert.equal(document.getElementById('rl-roll-inspector'),null,'Closing DIM removes the guide');
const next=document.createElement('div');next.className='item-popup';document.body.append(next);applyLens(next,near);
assert.equal(document.querySelectorAll('#rl-roll-inspector').length,1);
next.dataset.aegisItemType='armor';applyLens(next,near);assert.equal(document.getElementById('rl-roll-inspector'),null);
const fixed=payload();fixed.ownedRoll.randomizedTraits=false;host.innerHTML=rollInspectorHtml(fixed);
assert.match(host.textContent,/Fixed main traits/);assert.equal(host.querySelectorAll('.rl-inspector-slot').length,0);
assert.deepEqual(activityRecommendations('pve',fixed),[]);
const incomplete=payload();incomplete.sheetWeaponPvECandidates=[{...sheet,mw:''}];host.innerHTML=rollInspectorHtml(incomplete);
assert.match(host.querySelector('.rl-inspector-activity.rl-inspector-pve').textContent,/Source does not specify: Masterwork/);
assert.match(host.querySelector('.rl-inspector-activity.rl-inspector-pvp').textContent,/No compatible recommendation/);
incomplete.sheetWeaponPvECandidates=[sheet];incomplete.ownedRoll.slots.mag.complete=false;host.innerHTML=rollInspectorHtml(incomplete);
assert.match(host.textContent,/DIM data incomplete: Magazine/);assert.match(host.querySelector('[data-slot="mag"] .rl-inspector-slot-heading').textContent,/Undefined/);
incomplete.sourceResolutionPvE='ambiguous';host.innerHTML=rollInspectorHtml(incomplete);
assert.match(host.textContent,/cannot identify this weapon edition/);assert.equal(host.querySelectorAll('.rl-inspector-slot').length,0);
const malicious=payload();malicious.name='<img src=x onerror=alert(1)>';malicious.sheetWeaponPvECandidates=[{...sheet,notes:'<script>alert(1)</script>',perk1:'<b>Trait A</b>'}];host.innerHTML=rollInspectorHtml(malicious);
assert.equal(host.querySelector('img,script'),null);assert.match(host.textContent,/<script>/);
clearRollInspector();dom.window.close();
console.log('Inspector checks passed: both activities, inactive ownership, separate combinations, explanations, updates, dismissal, fixed/undefined data and escaping.');
