const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const { load, group, payload } = require('./lens-helpers.cjs');
const dom = new JSDOM('<!doctype html><body><div id="tile" data-aegis-item-hash="1" data-aegis-instance-id="demo-1"><div class="aegis-badge">S+</div></div></body>',{ pretendToBeVisual:true });
global.document=dom.window.document; global.HTMLElement=dom.window.HTMLElement;
const { applyLens, configureLens, initLensDashboard, lensCardHtml } = load('roll-lens-ui');
const tile=document.getElementById('tile'); const data=payload(group(),group());
configureLens({enabled:true,glow:true,rule:'traits'}); applyLens(tile,data);
assert.equal(tile.querySelector('.rl-badge').textContent,'BOTH');
assert.equal(tile.dataset.rlGlow,'on'); assert.equal(tile.dataset.rlUsage,'both');
const badge=tile.querySelector('.rl-badge'); applyLens(tile,data); assert.equal(tile.querySelector('.rl-badge'),badge);
assert.equal(tile.querySelectorAll('.rl-badge').length,1);
const near=payload(group(['active','active','missing','active'])); applyLens(tile,near);
assert.equal(tile.querySelector('.rl-badge').textContent,'PVE-1'); assert.equal(tile.dataset.rlGlow,'off');
const quiet=payload(group(['active','active','missing','missing'])); applyLens(tile,quiet);
assert.equal(tile.querySelector('.rl-badge'),null); assert.equal(tile.dataset.rlState,'partial');
const observer=new dom.window.MutationObserver(()=>{}); observer.observe(tile,{attributes:true,childList:true,subtree:true});
applyLens(tile,quiet); assert.equal(observer.takeRecords().length,0,'An unlabeled tile must settle without repeat DOM writes'); observer.disconnect();
applyLens(tile,data); assert.equal(tile.querySelector('.rl-badge').textContent,'BOTH');
configureLens({enabled:false}); applyLens(tile,data); assert.equal(tile.querySelector('.rl-badge'),null); assert.equal(tile.dataset.rlState,undefined);
configureLens({enabled:true}); data.name='<img src=x onerror=alert(1)>'; applyLens(tile,data);
const { evaluateLens }=load('roll-lens'); const card=lensCardHtml(data.name,evaluateLens(data));
assert.ok(card.includes('&lt;img')); assert.ok(!card.includes('<img src=x'));
const popup=document.createElement('div'); popup.className='item-popup'; popup.innerHTML='<button><h1>Weapon</h1></button>'; document.body.append(popup);
applyLens(popup,data); assert.equal(popup.querySelectorAll('.rl-item-card').length,1); assert.equal(popup.querySelector('.rl-item-card img'),null);
applyLens(popup,data); assert.equal(popup.querySelectorAll('.rl-item-card').length,1);
const map=new WeakMap([[tile,data]]); initLensDashboard(el=>map.get(el)); initLensDashboard(el=>map.get(el)); assert.equal(document.querySelectorAll('#rl-launcher').length,1);
const panel=document.getElementById('rl-dashboard'); panel.showModal=()=>{panel.open=true}; panel.close=()=>{panel.open=false; panel.dispatchEvent(new dom.window.Event('close'))};
document.getElementById('rl-launcher').click(); assert.equal(panel.open,true); assert.equal(document.activeElement.className,'rl-search');
assert.equal(panel.querySelectorAll('.rl-row').length,1); assert.match(panel.querySelector('.rl-coverage').textContent,/1 weapon instances currently loaded/);
panel.querySelector('[data-filter="unknown"]').click(); assert.equal(panel.querySelectorAll('.rl-row').length,0);
panel.querySelector('[data-filter="both"]').click(); assert.equal(panel.querySelectorAll('.rl-row').length,1);
panel.querySelector('.rl-row').click(); assert.ok(panel.querySelector('.rl-detail').textContent.includes('God roll'));
const search=panel.querySelector('.rl-search'); search.value='no-match'; search.dispatchEvent(new dom.window.Event('input')); assert.equal(panel.querySelectorAll('.rl-row').length,0);
panel.querySelector('.rl-close').click(); assert.equal(panel.open,false); assert.equal(document.getElementById('rl-launcher').getAttribute('aria-expanded'),'false');
dom.window.close(); console.log('DOM checks passed: badges, deduplication, enable/disable, HTML escaping, popup, counts, filters, search and dialog focus.');
