const assert=require('node:assert/strict');const {load,sheet,payload,group}=require('./lens-helpers.cjs');
const {resolveRollSourceCandidates}=load('roll-lens-source');const {evaluateLens}=load('roll-lens');
const origin=[{slot:'origin',hash:99,name:'Origin',active:true,icon:''}];
const first={...sheet,name:'Test weapon (Release A)',versionTag:'Release A',origin:'Origin'};
const second={...first,perk1:'Other A',perk2:'Other B'};
const db={weapons:{'test weapon':first},variants:{'test weapon':[first,second]}};
let resolved=resolveRollSourceCandidates(db,'Test weapon',1,origin);assert.equal(resolved.resolution,'resolved');assert.equal(resolved.rows.length,2,'Separate combinations for one edition remain separate candidates');
const d=payload(group(),group());d.sheetWeaponPvECandidates=[{...sheet,barrel:'Other barrel'},{...sheet,mag:'Other mag'}];d.sheetWeaponPvPCandidates=[{...sheet,barrel:'Other barrel'},{...sheet,mag:'Other mag'}];
assert.equal(evaluateLens(d).badge,'PVE-1 PVP-1','Two separate 4/5 rows cannot combine into 5/5');
const wrong=payload(group(),group());[wrong.ownedRoll.slots.perk1.plugs[0].name,wrong.ownedRoll.slots.perk2.plugs[0].name]=[wrong.ownedRoll.slots.perk2.plugs[0].name,wrong.ownedRoll.slots.perk1.plugs[0].name];assert.equal(evaluateLens(wrong).badge,'','Recommended traits in the wrong columns do not count');
const enhanced=payload(group(),group());enhanced.ownedRoll.slots.perk1.plugs[0].name='Enhanced Trait A';enhanced.ownedRoll.slots.perk2.plugs[0].name='Trait B (Enhanced)';assert.equal(evaluateLens(enhanced).badge,'BOTH');
resolved=resolveRollSourceCandidates({weapons:db.weapons,variants:{'test weapon':[first,{...first,name:'Test weapon (Release B)',versionTag:'Release B'}]}},'Test weapon',1,origin);assert.equal(resolved.resolution,'ambiguous','An origin shared by different editions cannot pick the most favorable roll');
const empty=payload(group(),group());empty.sheetWeaponPvECandidates=[];empty.sheetWeaponPvPCandidates=[];assert.equal(evaluateLens(empty).badge,'UNDEF','Explicitly unresolved candidates never borrow the legacy sheet selection');
const incomplete=payload(group(),group());incomplete.ownedRoll.slots.mag.complete=false;assert.equal(evaluateLens(incomplete).badge,'UNDEF');
const nearPriority=payload(group(['missing','active','active','active']));assert.equal(evaluateLens(nearPriority).badge,'PVE-1','4/5 takes priority over missing other-activity coverage');
const fixed=payload(group());fixed.sheetWeaponPvE={...sheet,source:'Exotic',mw:''};fixed.sheetWeaponPvECandidates=[fixed.sheetWeaponPvE];assert.equal(evaluateLens(fixed).badge,'UNDEF','An exotic viability tier cannot fabricate five-slot coverage');
const guard=payload(group(),group());guard.sheetWeaponPvE={...sheet,mw:'N/A'};guard.sheetWeaponPvP=null;guard.sheetWeaponPvECandidates=[guard.sheetWeaponPvE];guard.sheetWeaponPvPCandidates=[];assert.equal(evaluateLens(guard).badge,'UNDEF');
const newEdition={...first,name:'Test weapon (Release B)',versionTag:'Release B',perk1:'New A\nShared A',perk2:'New B',origin:'Origin'};
const oldEdition={...first,perk1:'Old A\nShared A',perk2:'Old B\nNew B'};
const pool={hash:123,name:'Test weapon',perkColumns:[['New A','Shared A'],['New B']]};
const editionsDb={weapons:db.weapons,variants:{'test weapon':[oldEdition,newEdition]}};
resolved=resolveRollSourceCandidates(editionsDb,'Test weapon',123,origin,pool);assert.equal(resolved.resolution,'resolved');assert.deepEqual(resolved.rows,[newEdition],'Exact hash pool resolves shared origin independently of favorable owned traits');
resolved=resolveRollSourceCandidates(editionsDb,'Test weapon',999,origin,pool);assert.equal(resolved.resolution,'ambiguous','Another weapon hash cannot supply identity');
resolved=resolveRollSourceCandidates(editionsDb,'Test weapon',undefined,origin);assert.equal(resolved.resolution,'ambiguous','Missing identity safely falls back to origin resolution');
resolved=resolveRollSourceCandidates(editionsDb,'Test weapon',123,origin,{...pool,name:'Different weapon'});assert.equal(resolved.resolution,'ambiguous','Another weapon name cannot supply identity');
resolved=resolveRollSourceCandidates(editionsDb,'Test weapon',123,origin,{...pool,perkColumns:undefined});assert.equal(resolved.resolution,'ambiguous','Missing manifest columns safely retain origin ambiguity');
const originsOnly={weapons:db.weapons,variants:{'test weapon':[{...first,origin:'Origin'},{...newEdition,origin:'Origin\nNew origin'}]}};
resolved=resolveRollSourceCandidates(originsOnly,'Test weapon',1,[...origin,{slot:'origin',hash:100,name:'New origin',active:false,icon:''}]);assert.deepEqual(resolved.rows,[originsOnly.variants['test weapon'][1]],'Full origin sets distinguish editions sharing a vendor trait');

// A generic source can lag behind an exact hash's perk pool and origin metadata.
const fs=require('node:fs');
const mintDb=JSON.parse(fs.readFileSync('data/pve-database.json','utf8'));
const mintWeapon=JSON.parse(fs.readFileSync('data/manifest-weapons.json','utf8')).find(w=>w.hash===3285784871);
const mintOrigins=mintWeapon.origins.map((name,i)=>({slot:'origin',hash:100+i,name,active:false,icon:''}));
const mintSource=JSON.stringify(mintDb.variants['mint retrograde']);
resolved=resolveRollSourceCandidates(mintDb,mintWeapon.name,mintWeapon.hash,mintOrigins,mintWeapon);
assert.equal(resolved.resolution,'resolved','Mint Retrograde retains valid PvE choices despite obsolete Slice and origin metadata');
assert.equal(resolved.rows[0].perk2,'Master of Arms\nChain Reaction','Unavailable source alternatives are omitted for this exact hash');
assert.equal(JSON.stringify(mintDb.variants['mint retrograde']),mintSource,'Source snapshots are never mutated');
const mintOwned=group();
['Quick Launch','Appended Mag','Beacon Rounds','Master of Arms','Reload'].forEach((name,i)=>mintOwned.slots[['barrel','mag','perk1','perk2','masterwork'][i]].plugs[0].name=name);
const mintPayload={...payload(mintOwned),name:mintWeapon.name,sheetWeaponPvECandidates:resolved.rows,sourceResolutionPvE:resolved.resolution};
assert.equal(evaluateLens(mintPayload).badge,'PVE','A retained whole combination still requires all five owned slots');
['Confined Launch','High-Velocity Rounds','Envious Arsenal','Frenzy','Blast Radius'].forEach((name,i)=>mintOwned.slots[['barrel','mag','perk1','perk2','masterwork'][i]].plugs[0].name=name);
assert.equal(evaluateLens(mintPayload).pve.matchedCount,0,'The reported gun is evaluated without treating unavailable or unrecommended perks as god rolls');
assert.equal(resolveRollSourceCandidates(mintDb,mintWeapon.name,1,mintOrigins,mintWeapon).resolution,'ambiguous','Stale origin recovery requires the exact item hash');
const stale={...sheet,origin:'Old origin',perk1:'Trait A\nRemoved A',perk2:'Trait B\nRemoved B'};
const staleDb={weapons:{'test weapon':stale},variants:{'test weapon':[stale]}};
const stalePool={hash:123,name:'Test weapon',perkColumns:[['Trait A'],['Trait B']]};
assert.equal(resolveRollSourceCandidates(staleDb,'Test weapon',123,origin,{...stalePool,perkColumns:[['Trait A'],['Unrelated B']]}).resolution,'ambiguous','One overlapping column cannot establish compatibility');
assert.equal(resolveRollSourceCandidates(staleDb,'Test weapon',123,origin,{...stalePool,perkColumns:[['Trait A'],[]]}).resolution,'ambiguous','Incomplete identity cannot recover stale metadata');
const staleEditions={...staleDb,variants:{'test weapon':[{...stale,name:'Test weapon (Release A)',versionTag:'Release A'},{...stale,name:'Test weapon (Release B)',versionTag:'Release B'}]}};
assert.equal(resolveRollSourceCandidates(staleEditions,'Test weapon',123,origin,stalePool).resolution,'ambiguous','Partial overlap cannot select among named editions');
const {buildOwnedRollData}=load('owned-rolls');
const fixedSocket={socketDefinition:{socketTypeHash:1215804697},hasRandomizedPlugItems:false,plugged:{plugDef:{hash:777,displayProperties:{name:'Trait A'},plug:{plugCategoryIdentifier:'frames'}}}};
assert.equal(buildOwnedRollData([fixedSocket]).randomizedTraits,false);
assert.equal(buildOwnedRollData([{...fixedSocket,hasRandomizedPlugItems:true}]).randomizedTraits,true);
assert.equal(buildOwnedRollData([{...fixedSocket,hasRandomizedPlugItems:undefined}]).randomizedTraits,undefined);
console.log('Source/ownership checks passed: whole combinations, exact columns, hash-based edition identity, fixed-trait metadata, unresolved isolation and label precedence.');
